# Generated by Django 3.2.6 on 2021-08-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Deactive')], default=True),
            preserve_default=False,
        ),
    ]
