# Generated by Django 3.2.6 on 2021-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='faculty.Student'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='faculty.Staff'),
        ),
    ]
