# Generated by Django 3.2.6 on 2021-08-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20210824_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='faculty.staff'),
            preserve_default=False,
        ),
    ]
